pipeline {
agent none
stages {
    // DEV
    stage('Build Dev') {
        agent {
            label {
                label 'dev'
                customWorkspace "/opt/go-app"
            }
        }
        steps {
            sh 'git pull'
        }
    }
        stage('Test Dev') {
            agent {
                label {
                    label 'dev'
                    customWorkspace "/opt/go-app"
            }
        }
        steps {
            sh 'go test ./...'
        }
    }

        stage('Deploy Dev') {
            agent {
                label {
                    label 'dev'
                    customWorkspace "/opt/go-app"
            }
        }
        steps {
            script {
                withEnv ( ['JENKINS_NODE_COOKIE=do_not_kill'] ) {
                    sh 'go run main.go &'
                }
            }
        }
    }

        // PRODUCTION
        stage('Build Production') {
            agent {
                label {
                    label 'production'
                    customWorkspace "/opt/go-app"
            }
        }
        steps {
            sh 'git pull'
        }
    }

        stage('Test Production') {
            agent {
                label {
                    label 'production'
                    customWorkspace "/opt/go-app"
            }
        }
        steps {
            sh 'go test ./...'
        }
    }

        stage('Deploy Production') {
            agent {
                label {
                    label 'production'
                    customWorkspace "/opt/go-app"
            }
        }
        steps {
            script {
                withEnv ( ['JENKINS_NODE_COOKIE=do_not_kill'] ) {
                    sh 'go run main.go &'
                }
            }
        }
    }


    }   
}