pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                git 'https://github.com/kodekloudhub/go-webapp-sample.git'
            }
        }
        stage('UAT') {
            steps {
                git 'https://github.com/kodekloudhub/go-webapp-sample.git'
            }
        }
}